# create 4 jobs , 
# first three jobs will return date 
# forth jobs depends on first three job 



name: challenge1

on : [ push ]

jobs:
 job1: 
   name: First Job
   runs-on: ubuntu-latest
   steps:
   - name: Step One
     run : date
 job2: 
   name: Second Job
   runs-on: windows-latest
   steps:
   - name: Step One
     run : date
 job3: 
   name: Third Job
   runs-on: macos-latest
   steps:
   - name: Step One
     run : date
 job4: 
   name: Forth Job
   needs : [ job1, job2, job3 ]
   runs-on: windows-latest
   steps:
   - name: Step One
     run: date
     
   
